server:  port: 8080  eureka:  instance:    hostname: localhost  client:    register-with-eureka: false    fetch-registry: false    service-url:      defaultZone: http://localhost:8761/eureka/
spring:
    jpa:
        show-sql: true
        hibernate.ddl-auto: update
        database-platform: org.hibernate.dialect.MySQL5Dialect

    datasource:
        url: "jdbc:mysql://localhost:3306/useraccess?useSSL=false"
        username: root
        password: 1234
        driverClassName: com.mysql.jdbc.Driver

jwt:
  secret: jwt__
  expiration: 60000
